export type RecipeCategory = 'завтрак' | 'обед' | 'ужин' | 'десерт' | 'выпечка' | 'супы' | 'салаты' | 'напитки' | 'закуски';

export type Recipe = {
  id: string;
  name: string;
  description: string;
  category: RecipeCategory;
  ingredients: string[];
  steps: string[];
  time: number;
  complexity: number;
  price: number;
  calories: number;
  protein: number;
  fats: number;
  carbs: number;
};

export const recipes: Recipe[] = [
  {
    id: '1',
    name: 'Омлет с помидорами',
    description: 'Классический завтрак за 10 минут',
    category: 'завтрак',
    ingredients: ['яйца', 'помидор', 'молоко', 'соль', 'масло'],
    steps: ['Взбейте яйца с молоком', 'Нарежьте помидоры', 'Жарьте 5 минут'],
    time: 10,
    complexity: 1,
    price: 1,
    calories: 220,
    protein: 14,
    fats: 16,
    carbs: 6
  },
  {
    id: '2',
    name: 'Овсянка с бананом',
    description: 'Полезный завтрак',
    category: 'завтрак',
    ingredients: ['овсянка', 'банан', 'молоко', 'мёд'],
    steps: ['Сварите овсянку', 'Добавьте банан и мёд'],
    time: 7,
    complexity: 1,
    price: 2,
    calories: 380,
    protein: 12,
    fats: 8,
    carbs: 65
  },
  {
    id: '3',
    name: 'Яичница-глазунья',
    description: 'Быстрый завтрак',
    category: 'завтрак',
    ingredients: ['яйца', 'масло', 'соль'],
    steps: ['Разогрейте сковороду', 'Разбейте яйца', 'Жарьте 3 минуты'],
    time: 5,
    complexity: 1,
    price: 1,
    calories: 180,
    protein: 12,
    fats: 14,
    carbs: 1
  },
  {
    id: '4',
    name: 'Творожная запеканка',
    description: 'Нежная запеканка',
    category: 'завтрак',
    ingredients: ['творог', 'яйца', 'сахар', 'мука'],
    steps: ['Смешайте ингредиенты', 'Запекайте 40 минут'],
    time: 50,
    complexity: 2,
    price: 2,
    calories: 290,
    protein: 18,
    fats: 12,
    carbs: 28
  },
  {
    id: '5',
    name: 'Сырники',
    description: 'Классика русской кухни',
    category: 'завтрак',
    ingredients: ['творог', 'яйца', 'мука', 'сахар'],
    steps: ['Смешайте творог с яйцом', 'Сформируйте сырники', 'Жарьте до золотистой корочки'],
    time: 20,
    complexity: 2,
    price: 2,
    calories: 380,
    protein: 22,
    fats: 14,
    carbs: 42
  },
  {
    id: '6',
    name: 'Панкейки',
    description: 'Американские блинчики',
    category: 'завтрак',
    ingredients: ['мука', 'яйца', 'молоко', 'сахар', 'разрыхлитель'],
    steps: ['Смешайте тесто', 'Жарьте на сковороде'],
    time: 25,
    complexity: 2,
    price: 2,
    calories: 520,
    protein: 14,
    fats: 12,
    carbs: 88
  },
  {
    id: '7',
    name: 'Тосты с авокадо',
    description: 'Модный завтрак',
    category: 'завтрак',
    ingredients: ['хлеб', 'авокадо', 'яйца', 'лимон'],
    steps: ['Поджарьте хлеб', 'Разомните авокадо', 'Сварите яйцо пашот'],
    time: 12,
    complexity: 2,
    price: 3,
    calories: 380,
    protein: 16,
    fats: 24,
    carbs: 28
  },
  {
    id: '8',
    name: 'Каша пшенная',
    description: 'Традиционная каша',
    category: 'завтрак',
    ingredients: ['пшено', 'молоко', 'масло', 'сахар'],
    steps: ['Промойте пшено', 'Варите на молоке 25 минут'],
    time: 30,
    complexity: 1,
    price: 1,
    calories: 320,
    protein: 9,
    fats: 11,
    carbs: 48
  },
  {
    id: '9',
    name: 'Гранола домашняя',
    description: 'Хрустящая гранола',
    category: 'завтрак',
    ingredients: ['овсянка', 'орехи', 'мёд', 'сухофрукты'],
    steps: ['Смешайте овсянку с мёдом', 'Запекайте 30 минут'],
    time: 40,
    complexity: 2,
    price: 3,
    calories: 480,
    protein: 12,
    fats: 22,
    carbs: 58
  },
  {
    id: '10',
    name: 'Греческий салат',
    description: 'Свежий салат',
    category: 'салаты',
    ingredients: ['огурец', 'помидор', 'фета', 'маслины', 'оливковое масло'],
    steps: ['Нарежьте овощи', 'Добавьте фету', 'Заправьте маслом'],
    time: 10,
    complexity: 1,
    price: 3,
    calories: 280,
    protein: 12,
    fats: 22,
    carbs: 11
  },
  {
    id: '11',
    name: 'Цезарь с курицей',
    description: 'Классический салат',
    category: 'салаты',
    ingredients: ['куриная грудка', 'салат', 'пармезан', 'сухарики', 'соус цезарь'],
    steps: ['Обжарьте курицу', 'Смешайте с салатом', 'Добавьте соус'],
    time: 20,
    complexity: 2,
    price: 4,
    calories: 450,
    protein: 34,
    fats: 28,
    carbs: 18
  },
  {
    id: '12',
    name: 'Оливье',
    description: 'Праздничный салат',
    category: 'салаты',
    ingredients: ['картофель', 'яйца', 'колбаса', 'огурец', 'морковь', 'майонез'],
    steps: ['Отварите овощи', 'Нарежьте кубиками', 'Заправьте майонезом'],
    time: 40,
    complexity: 2,
    price: 3,
    calories: 380,
    protein: 14,
    fats: 24,
    carbs: 28
  },
  {
    id: '13',
    name: 'Винегрет',
    description: 'Овощной салат',
    category: 'салаты',
    ingredients: ['свёкла', 'картофель', 'морковь', 'огурец', 'капуста', 'масло'],
    steps: ['Отварите овощи', 'Нарежьте кубиками', 'Заправьте маслом'],
    time: 35,
    complexity: 1,
    price: 2,
    calories: 180,
    protein: 4,
    fats: 8,
    carbs: 24
  },
  {
    id: '14',
    name: 'Капрезе',
    description: 'Итальянский салат',
    category: 'салаты',
    ingredients: ['помидор', 'моцарелла', 'базилик', 'оливковое масло'],
    steps: ['Нарежьте помидоры и моцареллу', 'Выложите слоями', 'Полейте маслом'],
    time: 5,
    complexity: 1,
    price: 3,
    calories: 280,
    protein: 14,
    fats: 22,
    carbs: 8
  },
  {
    id: '15',
    name: 'Селедка под шубой',
    description: 'Классический слоеный салат',
    category: 'салаты',
    ingredients: ['селедка', 'картофель', 'морковь', 'свёкла', 'яйца', 'майонез'],
    steps: ['Отварите овощи', 'Выкладывайте слоями', 'Смазывайте майонезом'],
    time: 50,
    complexity: 3,
    price: 3,
    calories: 320,
    protein: 16,
    fats: 20,
    carbs: 22
  },
  {
    id: '16',
    name: 'Борщ',
    description: 'Украинский суп',
    category: 'супы',
    ingredients: ['говядина', 'свёкла', 'картофель', 'капуста', 'морковь', 'лук'],
    steps: ['Сварите бульон', 'Добавьте овощи', 'Варите 40 минут'],
    time: 120,
    complexity: 4,
    price: 3,
    calories: 280,
    protein: 22,
    fats: 12,
    carbs: 24
  },
  {
    id: '17',
    name: 'Щи',
    description: 'Русский капустный суп',
    category: 'супы',
    ingredients: ['говядина', 'капуста', 'картофель', 'морковь', 'лук'],
    steps: ['Сварите бульон', 'Добавьте овощи', 'Варите 30 минут'],
    time: 90,
    complexity: 3,
    price: 2,
    calories: 240,
    protein: 18,
    fats: 10,
    carbs: 22
  },
  {
    id: '18',
    name: 'Солянка',
    description: 'Острый мясной суп',
    category: 'супы',
    ingredients: ['колбаса', 'мясо', 'огурец', 'лимон', 'маслины', 'томатная паста'],
    steps: ['Обжарьте мясо', 'Добавьте огурцы', 'Варите 40 минут'],
    time: 60,
    complexity: 3,
    price: 4,
    calories: 320,
    protein: 20,
    fats: 18,
    carbs: 20
  },
  {
    id: '19',
    name: 'Уха',
    description: 'Рыбный суп',
    category: 'супы',
    ingredients: ['семга', 'картофель', 'морковь', 'лук'],
    steps: ['Сварите бульон', 'Добавьте овощи', 'Положите рыбу'],
    time: 40,
    complexity: 2,
    price: 4,
    calories: 260,
    protein: 24,
    fats: 10,
    carbs: 18
  },
  {
    id: '20',
    name: 'Суп-пюре из брокколи',
    description: 'Кремовый суп',
    category: 'супы',
    ingredients: ['брокколи', 'картофель', 'лук', 'сливки'],
    steps: ['Отварите овощи', 'Взбейте блендером', 'Добавьте сливки'],
    time: 35,
    complexity: 2,
    price: 2,
    calories: 240,
    protein: 8,
    fats: 14,
    carbs: 22
  },
  {
    id: '21',
    name: 'Куриный суп',
    description: 'Простой домашний суп',
    category: 'супы',
    ingredients: ['курица', 'картофель', 'морковь', 'лук', 'вермишель'],
    steps: ['Сварите бульон', 'Добавьте овощи', 'Положите вермишель'],
    time: 60,
    complexity: 2,
    price: 2,
    calories: 220,
    protein: 16,
    fats: 8,
    carbs: 20
  },
  {
    id: '22',
    name: 'Том Ям',
    description: 'Тайский острый суп',
    category: 'супы',
    ingredients: ['креветки', 'лемонграсс', 'галангал', 'грибы', 'паста том ям'],
    steps: ['Вскипятите воду с специями', 'Добавьте пасту', 'Положите креветки'],
    time: 30,
    complexity: 3,
    price: 5,
    calories: 320,
    protein: 28,
    fats: 16,
    carbs: 18
  },
  {
    id: '23',
    name: 'Минестроне',
    description: 'Итальянский овощной суп',
    category: 'супы',
    ingredients: ['картофель', 'морковь', 'капуста', 'фасоль', 'паста', 'томат'],
    steps: ['Обжарьте овощи', 'Добавьте бульон', 'Варите 30 минут'],
    time: 40,
    complexity: 2,
    price: 2,
    calories: 260,
    protein: 10,
    fats: 6,
    carbs: 42
  },
  {
    id: '24',
    name: 'Куриная грудка гриль',
    description: 'Диетическое блюдо',
    category: 'обед',
    ingredients: ['куриная грудка', 'специи', 'чеснок', 'лимон'],
    steps: ['Замариновать курицу', 'Жарить на гриле 12 минут'],
    time: 30,
    complexity: 2,
    price: 3,
    calories: 320,
    protein: 52,
    fats: 12,
    carbs: 2
  },
  {
    id: '25',
    name: 'Спагетти Карбонара',
    description: 'Итальянская паста',
    category: 'обед',
    ingredients: ['спагетти', 'бекон', 'яйца', 'пармезан'],
    steps: ['Отварите пасту', 'Обжарьте бекон', 'Смешайте с яйцами'],
    time: 20,
    complexity: 3,
    price: 3,
    calories: 650,
    protein: 28,
    fats: 32,
    carbs: 58
  },
  {
    id: '26',
    name: 'Плов',
    description: 'Восточное блюдо',
    category: 'обед',
    ingredients: ['баранина', 'рис', 'морковь', 'лук', 'зира'],
    steps: ['Обжарьте мясо', 'Добавьте овощи', 'Засыпьте рис'],
    time: 90,
    complexity: 4,
    price: 4,
    calories: 520,
    protein: 28,
    fats: 22,
    carbs: 58
  },
  {
    id: '27',
    name: 'Котлеты домашние',
    description: 'Классические котлеты',
    category: 'обед',
    ingredients: ['фарш говяжий', 'лук', 'яйца', 'хлеб', 'чеснок'],
    steps: ['Смешайте фарш с луком', 'Сформируйте котлеты', 'Жарьте 15 минут'],
    time: 40,
    complexity: 2,
    price: 3,
    calories: 380,
    protein: 24,
    fats: 22,
    carbs: 18
  },
  {
    id: '28',
    name: 'Жареная картошка с грибами',
    description: 'Простое блюдо',
    category: 'обед',
    ingredients: ['картофель', 'грибы', 'лук', 'масло'],
    steps: ['Нарежьте картофель', 'Обжарьте с грибами', 'Готовьте 20 минут'],
    time: 30,
    complexity: 1,
    price: 2,
    calories: 280,
    protein: 8,
    fats: 12,
    carbs: 38
  },
  {
    id: '29',
    name: 'Лазанья',
    description: 'Итальянская запеканка',
    category: 'обед',
    ingredients: ['листы лазаньи', 'фарш говяжий', 'помидор', 'сыр', 'молоко'],
    steps: ['Приготовьте соус болоньезе', 'Выкладывайте слоями', 'Запекайте 40 минут'],
    time: 90,
    complexity: 4,
    price: 4,
    calories: 580,
    protein: 28,
    fats: 26,
    carbs: 54
  },
  {
    id: '30',
    name: 'Ризотто с грибами',
    description: 'Кремовый рис',
    category: 'обед',
    ingredients: ['рис арборио', 'грибы', 'белое вино', 'пармезан', 'бульон'],
    steps: ['Обжарьте рис', 'Постепенно добавляйте бульон', 'Готовьте 25 минут'],
    time: 40,
    complexity: 4,
    price: 4,
    calories: 480,
    protein: 14,
    fats: 16,
    carbs: 68
  },
  {
    id: '31',
    name: 'Пельмени',
    description: 'Русская классика',
    category: 'обед',
    ingredients: ['мука', 'яйца', 'фарш', 'лук'],
    steps: ['Замесите тесто', 'Слепите пельмени', 'Отварите 7 минут'],
    time: 90,
    complexity: 4,
    price: 2,
    calories: 420,
    protein: 18,
    fats: 16,
    carbs: 52
  },
  {
    id: '32',
    name: 'Голубцы',
    description: 'Фаршированная капуста',
    category: 'обед',
    ingredients: ['капуста', 'фарш', 'рис', 'томатная паста'],
    steps: ['Отварите капусту', 'Заверните фарш', 'Тушите 40 минут'],
    time: 90,
    complexity: 4,
    price: 2,
    calories: 340,
    protein: 16,
    fats: 14,
    carbs: 36
  },
  {
    id: '33',
    name: 'Стейк из говядины',
    description: 'Сочный стейк',
    category: 'ужин',
    ingredients: ['говядина', 'масло', 'специи'],
    steps: ['Разогрейте сковороду', 'Жарьте стейк 4 минуты с каждой стороны'],
    time: 15,
    complexity: 2,
    price: 5,
    calories: 480,
    protein: 42,
    fats: 32,
    carbs: 0
  },
  {
    id: '34',
    name: 'Лосось терияки',
    description: 'Рыба в соусе',
    category: 'ужин',
    ingredients: ['лосось', 'соус терияки', 'кунжут'],
    steps: ['Замариновать лосося', 'Обжарить 8 минут'],
    time: 25,
    complexity: 2,
    price: 5,
    calories: 380,
    protein: 42,
    fats: 18,
    carbs: 12
  },
  {
    id: '35',
    name: 'Шашлык из свинины',
    description: 'Шашлык на мангале',
    category: 'ужин',
    ingredients: ['свинина', 'лук', 'уксус', 'специи'],
    steps: ['Замариновать мясо', 'Жарить на углях 20 минут'],
    time: 180,
    complexity: 3,
    price: 4,
    calories: 480,
    protein: 32,
    fats: 36,
    carbs: 4
  },
  {
    id: '36',
    name: 'Утка по-пекински',
    description: 'Хрустящая утка',
    category: 'ужин',
    ingredients: ['утка', 'соус хойсин', 'огурец', 'блинчики'],
    steps: ['Запечь утку', 'Нарезать тонко', 'Подавать с соусом'],
    time: 60,
    complexity: 4,
    price: 5,
    calories: 620,
    protein: 38,
    fats: 42,
    carbs: 24
  },
  {
    id: '37',
    name: 'Жаркое из свинины',
    description: 'Тушеное мясо с картофелем',
    category: 'ужин',
    ingredients: ['свинина', 'картофель', 'лук', 'морковь'],
    steps: ['Обжарить мясо', 'Добавить овощи', 'Тушить 40 минут'],
    time: 60,
    complexity: 2,
    price: 2,
    calories: 420,
    protein: 26,
    fats: 18,
    carbs: 38
  },
  {
    id: '38',
    name: 'Рататуй',
    description: 'Овощное рагу',
    category: 'ужин',
    ingredients: ['баклажан', 'кабачок', 'помидор', 'перец'],
    steps: ['Нарезать овощи', 'Выложить слоями', 'Запекать 60 минут'],
    time: 75,
    complexity: 3,
    price: 3,
    calories: 180,
    protein: 5,
    fats: 8,
    carbs: 24
  },
  {
    id: '39',
    name: 'Пицца Маргарита',
    description: 'Классическая пицца',
    category: 'ужин',
    ingredients: ['тесто', 'моцарелла', 'томатный соус', 'базилик'],
    steps: ['Раскатать тесто', 'Намазать соусом', 'Запекать 12 минут'],
    time: 25,
    complexity: 2,
    price: 3,
    calories: 560,
    protein: 24,
    fats: 22,
    carbs: 64
  },
  {
    id: '40',
    name: 'Тирамису',
    description: 'Итальянский десерт',
    category: 'десерт',
    ingredients: ['маскарпоне', 'яйца', 'савоярди', 'кофе', 'какао'],
    steps: ['Взбить крем', 'Окунуть печенье в кофе', 'Выложить слоями'],
    time: 270,
    complexity: 3,
    price: 4,
    calories: 480,
    protein: 10,
    fats: 32,
    carbs: 38
  },
  {
    id: '41',
    name: 'Чизкейк',
    description: 'Творожный торт',
    category: 'десерт',
    ingredients: ['творожный сыр', 'печенье', 'яйца', 'сахар', 'сливки'],
    steps: ['Сделать основу', 'Взбить крем', 'Запекать 50 минут'],
    time: 300,
    complexity: 4,
    price: 4,
    calories: 420,
    protein: 12,
    fats: 28,
    carbs: 32
  },
  {
    id: '42',
    name: 'Блинчики',
    description: 'Тонкие блины',
    category: 'десерт',
    ingredients: ['мука', 'яйца', 'молоко', 'сахар'],
    steps: ['Замесить тесто', 'Жарить на сковороде'],
    time: 30,
    complexity: 2,
    price: 1,
    calories: 340,
    protein: 10,
    fats: 8,
    carbs: 58
  },
  {
    id: '43',
    name: 'Медовик',
    description: 'Торт с медом',
    category: 'десерт',
    ingredients: ['мука', 'мёд', 'яйца', 'сметана', 'сахар'],
    steps: ['Испечь коржи', 'Приготовить крем', 'Собрать торт'],
    time: 180,
    complexity: 4,
    price: 3,
    calories: 520,
    protein: 8,
    fats: 24,
    carbs: 68
  },
  {
    id: '44',
    name: 'Шоколадный брауни',
    description: 'Влажный пирог',
    category: 'десерт',
    ingredients: ['шоколад', 'масло', 'яйца', 'сахар', 'мука'],
    steps: ['Растопить шоколад', 'Смешать с яйцами', 'Запекать 25 минут'],
    time: 40,
    complexity: 2,
    price: 3,
    calories: 580,
    protein: 8,
    fats: 32,
    carbs: 64
  },
  {
    id: '45',
    name: 'Маффины',
    description: 'Кексы',
    category: 'десерт',
    ingredients: ['мука', 'яйца', 'молоко', 'шоколад', 'сахар'],
    steps: ['Смешать тесто', 'Разлить по формам', 'Выпекать 20 минут'],
    time: 35,
    complexity: 2,
    price: 2,
    calories: 380,
    protein: 8,
    fats: 18,
    carbs: 48
  },
  {
    id: '46',
    name: 'Эклеры',
    description: 'Заварные пирожные',
    category: 'десерт',
    ingredients: ['мука', 'яйца', 'масло', 'сливки', 'шоколад'],
    steps: ['Заварить тесто', 'Выпечь заготовки', 'Начинить кремом'],
    time: 90,
    complexity: 4,
    price: 3,
    calories: 450,
    protein: 9,
    fats: 28,
    carbs: 42
  },
  {
    id: '47',
    name: 'Хлеб белый',
    description: 'Домашний хлеб',
    category: 'выпечка',
    ingredients: ['мука', 'дрожжи', 'вода', 'соль', 'сахар'],
    steps: ['Замесить тесто', 'Оставить подняться', 'Выпекать 40 минут'],
    time: 180,
    complexity: 3,
    price: 1,
    calories: 280,
    protein: 9,
    fats: 2,
    carbs: 56
  },
  {
    id: '48',
    name: 'Фокачча',
    description: 'Итальянский хлеб',
    category: 'выпечка',
    ingredients: ['мука', 'дрожжи', 'оливковое масло', 'розмарин'],
    steps: ['Замесить тесто', 'Сделать вмятины', 'Выпекать 25 минут'],
    time: 110,
    complexity: 3,
    price: 1,
    calories: 320,
    protein: 8,
    fats: 12,
    carbs: 46
  },
  {
    id: '49',
    name: 'Булочки с корицей',
    description: 'Сладкая выпечка',
    category: 'выпечка',
    ingredients: ['мука', 'дрожжи', 'молоко', 'сахар', 'корица'],
    steps: ['Замесить тесто', 'Свернуть рулет', 'Выпекать 25 минут'],
    time: 120,
    complexity: 3,
    price: 2,
    calories: 420,
    protein: 10,
    fats: 14,
    carbs: 64
  },
  {
    id: '50',
    name: 'Круассаны',
    description: 'Французская выпечка',
    category: 'выпечка',
    ingredients: ['мука', 'масло', 'дрожжи', 'молоко'],
    steps: ['Сделать слоеное тесто', 'Свернуть рогалики', 'Выпекать 18 минут'],
    time: 240,
    complexity: 5,
    price: 3,
    calories: 460,
    protein: 8,
    fats: 24,
    carbs: 52
  },
  ...Array.from({ length: 250 }, (_, i) => {
    const id = (51 + i).toString();
    const types: Array<{cat: RecipeCategory; dishes: string[]}> = [
      {cat: 'завтрак', dishes: ['Творожники', 'Запеканка', 'Мюсли', 'Смузи боул', 'Яйца пашот', 'Хлопья с молоком', 'Гренки', 'Вафли', 'Бутерброды', 'Йогурт с фруктами']},
      {cat: 'обед', dishes: ['Макароны', 'Рис с овощами', 'Тефтели', 'Бефстроганов', 'Рагу', 'Отбивные', 'Гуляш', 'Азу', 'Паста', 'Фрикадельки']},
      {cat: 'ужин', dishes: ['Салат с курицей', 'Запеченная рыба', 'Овощи на пару', 'Курица в духовке', 'Омлет с сыром', 'Паста с морепродуктами', 'Рыбные котлеты', 'Куриные крылья', 'Стейк из индейки', 'Гратен']},
      {cat: 'десерт', dishes: ['Пирог', 'Печенье', 'Кекс', 'Пудинг', 'Мусс', 'Желе', 'Пончики', 'Эклеры', 'Профитроли', 'Панакота']},
      {cat: 'выпечка', dishes: ['Пирожки', 'Ватрушки', 'Кулебяка', 'Расстегаи', 'Беляши', 'Чебуреки', 'Самса', 'Хачапури', 'Лаваш', 'Багет']},
      {cat: 'супы', dishes: ['Рассольник', 'Харчо', 'Грибной суп', 'Сырный суп', 'Гороховый суп', 'Фасолевый суп', 'Свекольник', 'Лапша', 'Мисо суп', 'Том кха']},
      {cat: 'салаты', dishes: ['Морковный салат', 'Свекольный салат', 'Салат Цезарь', 'Салат с тунцом', 'Овощной салат', 'Мимоза', 'Крабовый салат', 'Нисуаз', 'Кобб салад', 'Табуле']},
      {cat: 'напитки', dishes: ['Смузи', 'Коктейль', 'Лимонад', 'Компот', 'Морс', 'Кисель', 'Квас', 'Чай']},
      {cat: 'закуски', dishes: ['Брускетта', 'Канапе', 'Тарталетки', 'Рулеты', 'Паштет', 'Сырная тарелка', 'Овощная нарезка']}
    ];
    
    const catIndex = i % types.length;
    const dishIndex = i % types[catIndex].dishes.length;
    const dish = types[catIndex].dishes[dishIndex];
    const category = types[catIndex].cat;
    
    const ingredients = ['яйца', 'молоко', 'мука', 'масло', 'соль', 'сахар', 'курица', 'картофель', 'морковь', 'лук'];
    const ingCount = 3 + (i % 4);
    
    return {
      id,
      name: `${dish} №${id}`,
      description: `Вкусное блюдо`,
      category,
      ingredients: ingredients.slice(0, ingCount),
      steps: ['Подготовить ингредиенты', 'Приготовить блюдо', 'Подать на стол'],
      time: 15 + (i % 12) * 10,
      complexity: 1 + (i % 4),
      price: 1 + (i % 4),
      calories: 200 + (i % 25) * 20,
      protein: 10 + (i % 20),
      fats: 5 + (i % 15),
      carbs: 20 + (i % 30)
    };
  })
];